### ISSUE TITLE
Coils details

### ISSUE THREAD

**Issue by alberto-cesare** [occupycars/BORGI-WheelHubMotor#3]
Hi,
fantastic project!
Can you give some details about coils? Numer of turns, number of wire per stand, wire thickness.

Thanks for your support!

Alberto

**Comment by lomg** [comment]
Hey Alberto,
the coils have 210 strands of 0.1mm enameled copperwire, each strand has 13 turns and is 4.6m long.

**Comment by alberto-cesare** [comment]
Thanks for informations,
Continue on this way!
